version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      
      # Install Docker client
      - setup_remote_docker:
          version: 20.10.24

      - run:
          name: Build Docker Image
          command: |
            docker build -t website-deploy .

      - run:
          name: Test Image by Running Container
          command: |
            docker run -d -p 8080:80 --name temp-container website-deploy
            sleep 5
            curl -I http://localhost:8080 || echo "Site did not respond"
          

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
